server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul:
  #ignored-services: microservicecloud-dept  #禁止真实路径访问microservicecloud-dept
  prefix: /tgy                              #访问前缀
  ignored-services: "*"                    #禁止直接通过微服务名字访问所有服务
  routes:
    mydept.serviceId: microservicecloud-dept   #真实访问名
    mydept.path: /mydept/**                     #访问别名

info:
  app.name: tgy-microcloud
  company.name: www.tgy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

