spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bits_cloud_disk?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234

redis:
 database: 0
 host: 127.0.1
 port: 6379
 password:
 pool:
   max-active: 20
   max-wait: -1
   min-idle: 2
 timeout: 0

logging:
  level:
    com.xsfapp.xcc: DEBUG
    org.mybatis: DEBUG